INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('ja! H-Milch 1,5% 1l', 0.68, 1, 'LITRE', 'DRINK', 'Germany','EURO','/assets/uploads/products/4.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('ja! Markenbutter 250g', 1.29, 250, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/5.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('ja! H-Milch 3,5% 1l', 0.78, 1, 'LITRE', 'DRINK', 'Germany','EURO','/assets/uploads/products/6.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('REWE Beste Wahl Eier Freiland weiß Klasse M-L 10 Stück', 2.35, 10, 'STUCK', 'FOOD', 'Germany','EURO','/assets/uploads/products/7.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('REWE Bio Frische Bio-Eier 6 Stück', 2.19, 6, 'STUCK', 'FOOD', 'Germany','EURO','/assets/uploads/products/8.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('ja! Hackfleisch gemischt 500g', 2.39, 500, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/9.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('ja! Gouda jung 48% Fett 400g', 2.29, 400, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/10.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('REWE Bio Fettarme H-Milch 1,5% 1l', 1.05, 1, 'LITRE', 'DRINK', 'Germany','EURO','/assets/uploads/products/11.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('ja! Delikatess-Kochschinken 200g', 1.19, 200, 'GRAM', 'DRINK', 'Germany','EURO','/assets/uploads/products/12.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('REWE Bio H-Vollmilch 3,8% 1l', 1.15, 1, 'LITRE', 'DRINK', 'Germany','EURO','/assets/uploads/products/13.jpg' );

INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('ja! Speisequark Magerstufe 500g', 0.83, 500, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/14.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Wiesenhof Geflügel-Mortadella 100g', 1.09, 100, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/15.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('ja! Frischkäse Natur Doppelrahmstufe 300g', 0.99, 300, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/16.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Tulip Bacon 125g', 1.89, 125, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/17.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Zott Monte Maxi Schoko 4x100g', 1.99, 400, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/18.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Merl Waldorfsalat 175g', 1.89, 175, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/19.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Merl Fleischsalat Delikatess 125g', 1.39, 125, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/20.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Chtaura Hummus Kichererbsenpaste Creme Dip 380g', 1.99, 380, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/21.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Kato SnackBalls Tomate Olive 200g', 2.99, 200, 'GRAM', 'DRINK', 'Germany','EURO','/assets/uploads/products/22.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Quorn Schwedische Hackbällchen 200g', 2.99, 200, 'GRAM', 'DRINK', 'Germany','EURO','/assets/uploads/products/23.jpg' );


INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Aroy-D Kokosnussmilch 2,9l', 11.63, 2.9, 'LITRE', 'DRINK', 'Germany','EURO','/assets/uploads/products/24.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Rocinante Queso de Cabra Ziegenhartkäse 200g', 6.89, 200, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/25.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Asian Homegourmet Würzpaste für koreanische KimchiSuppe 50g', 1.99, 50, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/26.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Royal Caramelo Liquido flüssiger Karamell 400g', 3.49, 400, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/27.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Garcia Barquero Semicurado Spanischer Mischkäse 250g', 6.47, 250, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/28.jpg' );
INSERT INTO product(productname, estunitprice, unit, unit_type, productgroup, country, currency, prodref) VALUES('Feinkost Käfer Wiesn Leberwurst Leberwurst 100 g', 5.95, 100, 'GRAM', 'FOOD', 'Germany','EURO','/assets/uploads/products/29.jpg' );
